add_newline = false

format = '$python$conda$directory$git_branch$git_status$character'

[python]
detect_extensions = []
detect_files = []
style = 'bold green'
symbol = ' '
format = '[\($symbol$virtualenv\)]($style) '

[conda]
ignore_base = false
style = 'bold green'
# symbol = ' '
format = '[\($symbol$environment\)]($style) '

[directory]
style = 'bold blue'

[git_branch]
style = 'bold yellow'
